version: "3"
services:
  estimate-frontend:
    image: node:16-alpine
    working_dir: /app
    env_file: .env
    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - ./node_modules:/node_modules
    ports:
      - "3000:3000"
    command: yarn start
    restart: unless-stopped
    tty: true

  estimate-backend:
    image: node:16-alpine
    working_dir: /app
    env_file: .env
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - ./node_modules:/node_modules
    ports:
      - "8080:8080"
    command: yarn watch
    restart: unless-stopped
    tty: true

  estimate-shared:
    image: node:16-alpine
    working_dir: /app
    env_file: .env
    volumes:
      - ./shared:/app
      - ./node_modules:/node_modules
    command: yarn watch
    restart: unless-stopped
    tty: true
